### ISSUE TITLE
Is new releases window needed?

### ISSUE THREAD

**Issue by SanderSade** [SanderSade/dlFilter#12]
This was only used for one specific bot afaik - and I don't think it exists anymore. I'll ask around about the bot/feature, but if you could do the same, please?

**Comment by Sophist-UK** [comment]
Haven't seen it on #ebooks so happy to drop this feature. Let me know.

**Comment by SanderSade** [comment]
It doesn't look like it is needed anymore.

**Comment by Sophist-UK** [comment]
Consider it gone.

**Comment by Sophist-UK** [comment]
Removed in #13.
