### ISSUE TITLE
@find is completely filtered out in 1.17 & 1.18

### ISSUE THREAD

**Issue by SanderSade** [SanderSade/dlFilter#14]
(creating a task to keep track on a bug discussed in e-mail)

- No one else's `@find`'s show up in DLF.filtered window
- Own `@find`' results are not captured to `DLF.@find.Results`
- Additionally, please verify that "Send to..." menu options still work

**Comment by Sophist-UK** [comment]
Yes - I know. On my list.

**Comment by Sophist-UK** [comment]
Fixed this lot.

Getting close to being ready for a full test. A few more things to do – 2-3 weeks perhaps.



From: Sander Säde 
Sent: Friday, June 9, 2017 9:06 AM
To: SanderSade/dlFilter 
Cc: Sophist ; Assign 
Subject: [SanderSade/dlFilter] @find is completely filtered out in 1.17 & 1.18 (#14)

(creating a task to keep track on a bug discussed in e-mail)

  a.. No one else's @find's show up in DLF.filtered window 
  b.. Own @find' results are not captured to DLF.@find.Results 
  c.. Additionally, please verify that "Send to..." menu options still work

**Comment by Sophist-UK** [comment]
Fixed in #13
