### ISSUE TITLE
Revise update check to go to GitHub

### ISSUE THREAD

**Issue by Sophist-UK** [SanderSade/dlFilter#3]

**Comment by SanderSade** [comment]
Also, as a part of this, replace dukelupus.com URL's with GitHub URLs. I even noticed one dukelupus.pri.ee link in code, and that site hasn't existed for ~7 years.

**Comment by Sophist-UK** [comment]
Yes - on my list (though not yet done.

**Comment by Sophist-UK** [comment]
Coded - see #7
