### ISSUE TITLE
Don't delete config variables on unload

### ISSUE THREAD

**Issue by Sophist-UK** [SanderSade/dlFilter#5]
Or at least ask the user whether to delete them.

**Comment by SanderSade** [comment]
Generally, if user wants to get rid of software, s/he does not want anything remaining on the system. So either delete silently or ask.

**Comment by Sophist-UK** [comment]
Yes - but sometime you unload temporarily and want to keep configuration.

**Comment by Sophist-UK** [comment]
Resolved in #7
