### ISSUE TITLE
Multinetwork support

### ISSUE THREAD

**Issue by Sophist-UK** [SanderSade/dlFilter#6]
Allow channels to filter to be of the form network#channel as well as #channel.

Provide separate filter windows per network as an option (and position filter windows with connection rather than at end).

**Comment by SanderSade** [comment]
Not sure about this - tbh, looks like a feature creep. 

I'd estimate that 99% of the users never set custom filters and most probably don't look at the filter output after initial "let me make sure this thing works" check.

**Comment by Sophist-UK** [comment]
This is not a custom filter - this is just about handling situation when mirc is connected to two IRC networks at the same time.

1. It needs to associate windows and echo messages with the right connection.
2. It is possible (though unlikely) that user would be connected to identically named channels on two networks and to want to filter one but not the other.

**Comment by Sophist-UK** [comment]
Fixed in #13
