### ISSUE TITLE
vNext-related topics

### ISSUE THREAD

**Issue by SanderSade** [SanderSade/dlFilter#9]
Let's have dlFilter.beta=x.xx in version file, and pre-release & beta versions can check update against that line. I.e.
```
dlFilter.beta=1.18
dlFilter=1.17
```
That way we can have "release" and "beta" channels.

**Comment by Sophist-UK** [comment]
Good idea - will need a check for beta versions dialog option

**Comment by Sophist-UK** [comment]
Done in #13

**Comment by SanderSade** [comment]
Leaving this issue open until vNext is out, for various miscellaneous small comments or tasks that don't merit an issue of their own.

**Comment by SanderSade** [comment]
Alias dlf.debug should not be local (-l), as that prevents user running it.

**Comment by SanderSade** [comment]
- in dlf.debug, variable count is off (shows -1)
- same, hash table size uses $hget(%cnter).size, which gives the total size. Let's add  $hget(%cnter, 0).item which would give the number of items

**Comment by Sophist-UK** [comment]
Variables count doesn't work at all for me. Looking in the wrong ini file as far as I can tell.

Hash tables - fixed.

**Comment by Sophist-UK** [comment]
Variables fixed - uses $var rather than an ini file to get variable values.

Also improved the connection details to support multi-server.

**Comment by Sophist-UK** [comment]
Fixed in #13
